
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 41;
  public static final int Op_BOOLEANO = 29;
  public static final int JAVA = 12;
  public static final int Sn_SALIDA = 30;
  public static final int CASE = 19;
  public static final int PRIVATE = 14;
  public static final int CORCHETE_C = 36;
  public static final int D_PUNTOS = 39;
  public static final int CORCHETE_A = 35;
  public static final int LLAVE_C = 34;
  public static final int FOR = 10;
  public static final int Op_LOGICO = 25;
  public static final int LLAVE_A = 33;
  public static final int IDENTIFICADOR = 40;
  public static final int IGUAL = 22;
  public static final int Op_ATRIBUCION = 27;
  public static final int CLASS = 20;
  public static final int Sn_THIS = 42;
  public static final int IF = 6;
  public static final int EOF = 0;
  public static final int T_DATO = 3;
  public static final int COMILLAS = 2;
  public static final int error = 1;
  public static final int UTIL = 13;
  public static final int CADENA = 5;
  public static final int Op_INCREMENTO = 28;
  public static final int SWITCH = 18;
  public static final int NUEVO = 21;
  public static final int IMPORT = 11;
  public static final int ELSE = 7;
  public static final int PUNTO = 38;
  public static final int Op_RELACIONAL = 26;
  public static final int PROTECTED = 16;
  public static final int PARENTESIS_C = 32;
  public static final int FINAL = 17;
  public static final int WHILE = 9;
  public static final int PARENTESIS_A = 31;
  public static final int PUBLIC = 15;
  public static final int P_COMA = 37;
  public static final int Op_MATEMATICO = 23;
  public static final int OBJETOS = 4;
  public static final int DO = 8;
  public static final int MULTIPLICACION = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLAS",
  "T_DATO",
  "OBJETOS",
  "CADENA",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "IMPORT",
  "JAVA",
  "UTIL",
  "PRIVATE",
  "PUBLIC",
  "PROTECTED",
  "FINAL",
  "SWITCH",
  "CASE",
  "CLASS",
  "NUEVO",
  "IGUAL",
  "Op_MATEMATICO",
  "MULTIPLICACION",
  "Op_LOGICO",
  "Op_RELACIONAL",
  "Op_ATRIBUCION",
  "Op_INCREMENTO",
  "Op_BOOLEANO",
  "Sn_SALIDA",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "P_COMA",
  "PUNTO",
  "D_PUNTOS",
  "IDENTIFICADOR",
  "NUMERO",
  "Sn_THIS"
  };
}

