
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.Analizadores.Html;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTABLA = 11;
  public static final int NUMERO = 40;
  public static final int FINCOLUMT = 20;
  public static final int MENORQ = 5;
  public static final int SCORE = 26;
  public static final int FINCOLUMD = 22;
  public static final int INCOLUMT = 19;
  public static final int CORCHETE_C = 34;
  public static final int D_PUNTOS = 38;
  public static final int CORCHETE_A = 33;
  public static final int LLAVE_C = 32;
  public static final int INHTML = 7;
  public static final int ITERADOR = 14;
  public static final int FOR = 13;
  public static final int LLAVE_A = 31;
  public static final int HASTA = 15;
  public static final int IDENTIFICADOR = 39;
  public static final int IGUAL = 27;
  public static final int INCOLUMD = 21;
  public static final int FINHTML = 8;
  public static final int FINFOR = 16;
  public static final int FINTABLA = 12;
  public static final int EOF = 0;
  public static final int T_DATO = 3;
  public static final int COMILLAS = 2;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int RESULTADO = 25;
  public static final int CADENA = 4;
  public static final int ETIQUETA1 = 9;
  public static final int FINFILCOLUM = 18;
  public static final int ERROR = 41;
  public static final int DOBLEDOLAR = 24;
  public static final int PUNTO = 37;
  public static final int MAYORQ = 6;
  public static final int PARENTESIS_C = 30;
  public static final int PARENTESIS_A = 29;
  public static final int SALTOLINEA = 23;
  public static final int INIFILCOLUM = 17;
  public static final int P_COMA = 35;
  public static final int FINETIQUETA = 10;
  public static final int Op_MATEMATICO = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLAS",
  "T_DATO",
  "CADENA",
  "MENORQ",
  "MAYORQ",
  "INHTML",
  "FINHTML",
  "ETIQUETA1",
  "FINETIQUETA",
  "INTABLA",
  "FINTABLA",
  "FOR",
  "ITERADOR",
  "HASTA",
  "FINFOR",
  "INIFILCOLUM",
  "FINFILCOLUM",
  "INCOLUMT",
  "FINCOLUMT",
  "INCOLUMD",
  "FINCOLUMD",
  "SALTOLINEA",
  "DOBLEDOLAR",
  "RESULTADO",
  "SCORE",
  "IGUAL",
  "Op_MATEMATICO",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "P_COMA",
  "COMA",
  "PUNTO",
  "D_PUNTOS",
  "IDENTIFICADOR",
  "NUMERO",
  "ERROR"
  };
}

